export const ADDRESSES = {
  BATTLE_MANAGER: import.meta.env.VITE_BATTLE_MANAGER_ADDRESS || "",
  BETTING_POOL: import.meta.env.VITE_BETTING_POOL_ADDRESS || "",
  STAKING_POOL: import.meta.env.VITE_STAKING_POOL_ADDRESS || "",
  ORACLE: import.meta.env.VITE_ORACLE_ADDRESS || "",
  COC_TOKEN: import.meta.env.VITE_COC_TOKEN_ADDRESS || "",
};

export const ABIS = {
  BattleManager: [
    {
      type: "constructor",
      inputs: [
        {
          name: "_clinkersNFT",
          type: "address",
          internalType: "address",
        },
        { name: "_cocToken", type: "address", internalType: "address" },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "accessMode",
      inputs: [],
      outputs: [
        {
          name: "",
          type: "uint8",
          internalType: "enum BattleManager.AccessMode",
        },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "activeBattles",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "battleCounter",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "battles",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [
        { name: "id", type: "uint256", internalType: "uint256" },
        { name: "token1", type: "address", internalType: "address" },
        { name: "token2", type: "address", internalType: "address" },
        { name: "deployer1", type: "address", internalType: "address" },
        { name: "deployer2", type: "address", internalType: "address" },
        { name: "startTime", type: "uint256", internalType: "uint256" },
        { name: "endTime", type: "uint256", internalType: "uint256" },
        {
          name: "status",
          type: "uint8",
          internalType: "enum BattleManager.BattleStatus",
        },
        {
          name: "theme",
          type: "uint8",
          internalType: "enum BattleManager.BattleTheme",
        },
        { name: "winner", type: "address", internalType: "address" },
        { name: "totalBets", type: "uint256", internalType: "uint256" },
        { name: "spotlightBattle", type: "bool", internalType: "bool" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "bettingPool",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "cancelExpiredBattle",
      inputs: [{ name: "_battleId", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "clinkersNFT",
      inputs: [],
      outputs: [
        { name: "", type: "address", internalType: "contract IERC721" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "cocToken",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "completeBattle",
      inputs: [{ name: "_battleId", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "createBattle",
      inputs: [
        { name: "_token1", type: "address", internalType: "address" },
        { name: "_token2", type: "address", internalType: "address" },
        { name: "_deployer1", type: "address", internalType: "address" },
        { name: "_deployer2", type: "address", internalType: "address" },
        { name: "_duration", type: "uint256", internalType: "uint256" },
        {
          name: "_theme",
          type: "uint8",
          internalType: "enum BattleManager.BattleTheme",
        },
        { name: "_spotlightBattle", type: "bool", internalType: "bool" },
      ],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "getActiveBattles",
      inputs: [],
      outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "gracePeriod",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "hasAccess",
      inputs: [{ name: "_user", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "minCOCHolding",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "oracle",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "owner",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "recordBet",
      inputs: [
        { name: "_battleId", type: "uint256", internalType: "uint256" },
        { name: "_amount", type: "uint256", internalType: "uint256" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "renounceOwnership",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "setAccessMode",
      inputs: [
        {
          name: "_mode",
          type: "uint8",
          internalType: "enum BattleManager.AccessMode",
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "setBettingPool",
      inputs: [
        { name: "_bettingPool", type: "address", internalType: "address" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "setGracePeriod",
      inputs: [
        { name: "_gracePeriod", type: "uint256", internalType: "uint256" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "setMinCOCHolding",
      inputs: [
        {
          name: "_minCOCHolding",
          type: "uint256",
          internalType: "uint256",
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "setOracle",
      inputs: [{ name: "_oracle", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "transferOwnership",
      inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "event",
      name: "AccessModeUpdated",
      inputs: [
        {
          name: "newMode",
          type: "uint8",
          indexed: false,
          internalType: "enum BattleManager.AccessMode",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "BattleCancelled",
      inputs: [
        {
          name: "battleId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "BattleCompleted",
      inputs: [
        {
          name: "battleId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "winner",
          type: "address",
          indexed: false,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "BattleCreated",
      inputs: [
        {
          name: "battleId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "token1",
          type: "address",
          indexed: false,
          internalType: "address",
        },
        {
          name: "token2",
          type: "address",
          indexed: false,
          internalType: "address",
        },
        {
          name: "deployer1",
          type: "address",
          indexed: false,
          internalType: "address",
        },
        {
          name: "deployer2",
          type: "address",
          indexed: false,
          internalType: "address",
        },
        {
          name: "startTime",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "endTime",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "theme",
          type: "uint8",
          indexed: false,
          internalType: "enum BattleManager.BattleTheme",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "BattleStarted",
      inputs: [
        {
          name: "battleId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "timestamp",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "BettingPoolUpdated",
      inputs: [
        {
          name: "newBettingPool",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "MinCOCHoldingUpdated",
      inputs: [
        {
          name: "newMinCOCHolding",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OracleUpdated",
      inputs: [
        {
          name: "newOracle",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          name: "previousOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "newOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "error",
      name: "OwnableInvalidOwner",
      inputs: [{ name: "owner", type: "address", internalType: "address" }],
    },
    {
      type: "error",
      name: "OwnableUnauthorizedAccount",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  ],
  BettingPool: [
    {
      type: "constructor",
      inputs: [
        {
          name: "_battleManager",
          type: "address",
          internalType: "address",
        },
        { name: "_cocToken", type: "address", internalType: "address" },
        {
          name: "_minBetAmount",
          type: "uint256",
          internalType: "uint256",
        },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "battleExposureCommitted",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "battleFeesDistributed",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "battleManager",
      inputs: [],
      outputs: [
        {
          name: "",
          type: "address",
          internalType: "contract BattleManager",
        },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "battleTotalPoolSnapshot",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "battleWinnerPoolSnapshot",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "battleWinnerTokenSnapshot",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "betCounter",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "bets",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [
        { name: "battleId", type: "uint256", internalType: "uint256" },
        { name: "bettor", type: "address", internalType: "address" },
        {
          name: "predictedWinner",
          type: "address",
          internalType: "address",
        },
        { name: "amount", type: "uint256", internalType: "uint256" },
        { name: "leverage", type: "uint256", internalType: "uint256" },
        { name: "timestamp", type: "uint256", internalType: "uint256" },
        { name: "settled", type: "bool", internalType: "bool" },
        { name: "cashedOut", type: "bool", internalType: "bool" },
        { name: "liquidated", type: "bool", internalType: "bool" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "cashOutBet",
      inputs: [{ name: "_betId", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "cocToken",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "deployerFeeBps",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "depositReserve",
      inputs: [{ name: "_amount", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "finalizeBattle",
      inputs: [{ name: "_battleId", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "getMaxLeverage",
      inputs: [{ name: "_battleId", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getOdds",
      inputs: [{ name: "_battleId", type: "uint256", internalType: "uint256" }],
      outputs: [
        { name: "token1", type: "address", internalType: "address" },
        { name: "token2", type: "address", internalType: "address" },
        { name: "odds1", type: "uint256", internalType: "uint256" },
        { name: "odds2", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getUserBets",
      inputs: [{ name: "_user", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "liquidate",
      inputs: [{ name: "_betId", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "maxLeverage",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "minBetAmount",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "minPoolForLeverage",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "openBets",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "owner",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "placeBet",
      inputs: [
        { name: "_battleId", type: "uint256", internalType: "uint256" },
        {
          name: "_predictedWinner",
          type: "address",
          internalType: "address",
        },
        { name: "_amount", type: "uint256", internalType: "uint256" },
        { name: "_leverage", type: "uint256", internalType: "uint256" },
      ],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "platformFeeBps",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "platformReserve",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "platformWallet",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "pools",
      inputs: [
        { name: "", type: "uint256", internalType: "uint256" },
        { name: "", type: "address", internalType: "address" },
      ],
      outputs: [
        { name: "totalAmount", type: "uint256", internalType: "uint256" },
        { name: "betCount", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "renounceOwnership",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "setMinPoolForLeverage",
      inputs: [
        {
          name: "_minPoolForLeverage",
          type: "uint256",
          internalType: "uint256",
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "setPlatformWallet",
      inputs: [
        {
          name: "_platformWallet",
          type: "address",
          internalType: "address",
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "setStakingContract",
      inputs: [
        {
          name: "_stakingContract",
          type: "address",
          internalType: "address",
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "settleBet",
      inputs: [{ name: "_betId", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "stakerFeeBps",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "stakingContract",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "totalCommittedExposure",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "totalOpenExposure",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "totalPooledAmount",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "transferOwnership",
      inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "updateFees",
      inputs: [
        {
          name: "_winnerPoolBps",
          type: "uint256",
          internalType: "uint256",
        },
        {
          name: "_deployerFeeBps",
          type: "uint256",
          internalType: "uint256",
        },
        {
          name: "_platformFeeBps",
          type: "uint256",
          internalType: "uint256",
        },
        {
          name: "_stakerFeeBps",
          type: "uint256",
          internalType: "uint256",
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "userBets",
      inputs: [
        { name: "", type: "address", internalType: "address" },
        { name: "", type: "uint256", internalType: "uint256" },
      ],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "winnerPoolBps",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "withdrawReserve",
      inputs: [{ name: "_amount", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "event",
      name: "BetCashedOut",
      inputs: [
        {
          name: "betId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "BetLiquidated",
      inputs: [
        {
          name: "betId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "BetPlaced",
      inputs: [
        {
          name: "betId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "battleId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "bettor",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "predictedWinner",
          type: "address",
          indexed: false,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "leverage",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "BetSettled",
      inputs: [
        {
          name: "betId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "payout",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "MinPoolForLeverageUpdated",
      inputs: [
        {
          name: "newMinPoolForLeverage",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          name: "previousOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "newOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "PlatformWalletUpdated",
      inputs: [
        {
          name: "newPlatformWallet",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ReserveDeposited",
      inputs: [
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ReserveWithdrawn",
      inputs: [
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "StakingContractUpdated",
      inputs: [
        {
          name: "newStakingContract",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "error",
      name: "OwnableInvalidOwner",
      inputs: [{ name: "owner", type: "address", internalType: "address" }],
    },
    {
      type: "error",
      name: "OwnableUnauthorizedAccount",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  ],
  StakingPool: [
    {
      type: "constructor",
      inputs: [
        { name: "_cocToken", type: "address", internalType: "address" },
        { name: "_clinkersNFT", type: "address", internalType: "address" },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "claimRewards",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "clinkersNFT",
      inputs: [],
      outputs: [
        { name: "", type: "address", internalType: "contract IERC721" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "cocToken",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "fundRewardPool",
      inputs: [{ name: "_amount", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "getPendingRewards",
      inputs: [{ name: "_user", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getVotingPower",
      inputs: [{ name: "_user", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "nftStakeOwner",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "nftStakes",
      inputs: [
        { name: "", type: "address", internalType: "address" },
        { name: "", type: "uint256", internalType: "uint256" },
      ],
      outputs: [
        { name: "tokenId", type: "uint256", internalType: "uint256" },
        { name: "timestamp", type: "uint256", internalType: "uint256" },
        {
          name: "lastClaimTime",
          type: "uint256",
          internalType: "uint256",
        },
        { name: "votingPower", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "owner",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "renounceOwnership",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "rewardPool",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "rewardRatePerSecond",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "stakeCOC",
      inputs: [{ name: "_amount", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "stakeNFT",
      inputs: [{ name: "_tokenId", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "stakes",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [
        { name: "amount", type: "uint256", internalType: "uint256" },
        { name: "timestamp", type: "uint256", internalType: "uint256" },
        {
          name: "lastClaimTime",
          type: "uint256",
          internalType: "uint256",
        },
        { name: "votingPower", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "totalCOCStaked",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "totalNFTsStaked",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "totalVotingPower",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "transferOwnership",
      inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "unstakeCOC",
      inputs: [{ name: "_amount", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "unstakeNFT",
      inputs: [{ name: "_tokenId", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "event",
      name: "COCStaked",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "COCUnstaked",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "NFTStaked",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "tokenId",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "NFTUnstaked",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "tokenId",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          name: "previousOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "newOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "RewardPoolFunded",
      inputs: [
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "RewardsClaimed",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "error",
      name: "OwnableInvalidOwner",
      inputs: [{ name: "owner", type: "address", internalType: "address" }],
    },
    {
      type: "error",
      name: "OwnableUnauthorizedAccount",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
    { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
    {
      type: "error",
      name: "SafeERC20FailedOperation",
      inputs: [{ name: "token", type: "address", internalType: "address" }],
    },
  ],
  TokenMetricsOracle: [
    { type: "constructor", inputs: [], stateMutability: "nonpayable" },
    {
      type: "function",
      name: "MAX_METRICS_AGE",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "battleManager",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "compareTokens",
      inputs: [
        { name: "_token1", type: "address", internalType: "address" },
        { name: "_token2", type: "address", internalType: "address" },
      ],
      outputs: [
        { name: "winner", type: "address", internalType: "address" },
        { name: "score1", type: "uint256", internalType: "uint256" },
        { name: "score2", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getMetrics",
      inputs: [{ name: "_token", type: "address", internalType: "address" }],
      outputs: [
        {
          name: "",
          type: "tuple",
          internalType: "struct TokenMetricsOracle.Metrics",
          components: [
            {
              name: "volumeUSD24h",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "priceUSD",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "liquidityUSD",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "txCount24h",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getMetricsTimestamp",
      inputs: [{ name: "_token", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "hasValidMetrics",
      inputs: [{ name: "_token", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "owner",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "renounceOwnership",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "setBattleManager",
      inputs: [
        {
          name: "_battleManager",
          type: "address",
          internalType: "address",
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "submitBatchMetrics",
      inputs: [
        { name: "_tokens", type: "address[]", internalType: "address[]" },
        {
          name: "_volumeUSD24h",
          type: "uint256[]",
          internalType: "uint256[]",
        },
        {
          name: "_priceUSD",
          type: "uint256[]",
          internalType: "uint256[]",
        },
        {
          name: "_liquidityUSD",
          type: "uint256[]",
          internalType: "uint256[]",
        },
        {
          name: "_txCount24h",
          type: "uint256[]",
          internalType: "uint256[]",
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "submitMetrics",
      inputs: [
        { name: "_token", type: "address", internalType: "address" },
        {
          name: "_volumeUSD24h",
          type: "uint256",
          internalType: "uint256",
        },
        { name: "_priceUSD", type: "uint256", internalType: "uint256" },
        {
          name: "_liquidityUSD",
          type: "uint256",
          internalType: "uint256",
        },
        { name: "_txCount24h", type: "uint256", internalType: "uint256" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "tokenMetrics",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [
        {
          name: "volumeUSD24h",
          type: "uint256",
          internalType: "uint256",
        },
        { name: "priceUSD", type: "uint256", internalType: "uint256" },
        {
          name: "liquidityUSD",
          type: "uint256",
          internalType: "uint256",
        },
        { name: "txCount24h", type: "uint256", internalType: "uint256" },
        { name: "timestamp", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "transferOwnership",
      inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "event",
      name: "BattleManagerUpdated",
      inputs: [
        {
          name: "newBattleManager",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "MetricsUpdated",
      inputs: [
        {
          name: "token",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "volumeUSD24h",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "priceUSD",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "liquidityUSD",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "txCount24h",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          name: "previousOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "newOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "error",
      name: "OwnableInvalidOwner",
      inputs: [{ name: "owner", type: "address", internalType: "address" }],
    },
    {
      type: "error",
      name: "OwnableUnauthorizedAccount",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
  ],
  ERC20: [
    "function balanceOf(address) view returns (uint256)",
    "function approve(address spender, uint256 amount) returns (bool)",
    "function allowance(address owner, address spender) view returns (uint256)",
    "function symbol() view returns (string)",
    "function decimals() view returns (uint8)",
  ],
};
